### PR TITLE
[Build] gitignore even more output from the build process on a 5.8 kernel

### PR DESCRIPTION
**Pull request by donporter**
This came up in testing v13 of the FSGSBASE patch series.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/24)

### CODE REVIEW

**Review by yamahata — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/24)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Comment by donporter** [comment]
This is paired with PR #1649 of Graphene: https://github.com/oscarlab/graphene/pull/1649

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/24)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/24)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/24)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/24)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
