### PR TITLE
Fix bundle

### PR DESCRIPTION
**Pull request by jiazhang0**
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)

### CODE REVIEW

**Review by yamahata — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by yamahata — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jiazhang0)

___
*[gsgx_fsgsbase.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9#-LsrYt_b8a0UCfF2vFvT:-LsrYt_c3MJz5f4zFbMl:brrzcv8) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/238720a8483ca9591e57c86b7242e73f54327881/gsgx_fsgsbase.c#L37)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	preempt_disable();
> 	__enable_fsgsbase(NULL);
> 	smp_call_function(__enable_fsgsbase, NULL, 1);
> 	preempt_enable();
> ```
</details>


on_each_cpu() can be used.

**Review by jiazhang0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @yamahata)

___
*[gsgx_fsgsbase.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9#-LsrYt_b8a0UCfF2vFvT:-Lst9y6t6eQDt02aiH6k:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/238720a8483ca9591e57c86b7242e73f54327881/gsgx_fsgsbase.c#L37)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> 	preempt_disable();
> 	__enable_fsgsbase(NULL);
> 	smp_call_function(__enable_fsgsbase, NULL, 1);
> 	preempt_enable();
> ```

on_each_cpu() can be used.
</blockquote></details>

Done.

**Review by yamahata — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jiazhang0)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9#-LsyCxYZDjKcn6lKCBvn:-LsyCxYZDjKcn6lKCBvo:b-6pn3w) (no related file):*
Note to myself: check locally that this change works. (Jenkins has its own SGX driver, so Jenkins won't report any issues on this.)

---
___
*[gsgx_main.c, line 94 at r2](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9#-LsyCnEC7YxmlBtL1UIX:-LsyCnEC7YxmlBtL1UIY:b-wzkwa2) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/8e0ed5a46faec8eefe5cf13692194bfb320177af/gsgx_main.c#L94)):*
> ```C
> 
> 	if (!boot_cpu_has(X86_FEATURE_FSGSBASE)) {
> 		pr_err("FSGSBASE feature depended by Graphene-SGX is unsupported\n");
> ```

`depended by` -> `required by`
`is unsupported` -> `is not supported by this CPU`

**Review by jiazhang0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jiazhang0, and @yamahata)

___
*[gsgx_main.c, line 94 at r2](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9#-LsyCnEC7YxmlBtL1UIX:-LsyIUhCBw6WT7QSgamn:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/8e0ed5a46faec8eefe5cf13692194bfb320177af/gsgx_main.c#L94)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`depended by` -> `required by`
`is unsupported` -> `is not supported by this CPU`
</blockquote></details>

Done.

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jiazhang0)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9#-LsyCxYZDjKcn6lKCBvn:-Lt289Mu-hCax_mAj1b7:b-rf8yrd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Note to myself: check locally that this change works. (Jenkins has its own SGX driver, so Jenkins won't report any issues on this.)
</blockquote></details>

Done. I verified locally, this change works correctly.

---

**Review by mkow — DISMISSED** [review]
Nice catch, thanks.

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9#-:-Lt2A5-O2CsiqJ_o3jL4:b-m16fak)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Comment by jiazhang0** [comment]
Squashed with a force-push.

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by yamahata — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by yamahata — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by donporter — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
