### PR TITLE
Ignore *.o.ur-safe files

### PR DESCRIPTION
**Pull request by donporter**
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/5)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
Just out of curiosity: what are `ur-safe` files?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/5#-:-LlXoOzI2pV7UBZiwViw:b4tp1wu)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/5)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
@dimakuv The internet says something about a new Ubuntu, but I'm not sure what are they exactly.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/5#-:-Ll_BDyc4pQh8ruRAaZ9:belw97h)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/5)* status: all files reviewed, 1 unresolved discussion (waiting on @donporter)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/5#-Ln-z0kO-B9aEtUHkAuC:-Ln-z0kO-B9aEtUHkAuD:b-z05npg) (no related file):*
@donporter Could you create a matching PR in the main repo?

---

**Review by donporter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/5)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/5#-Ln-z0kO-B9aEtUHkAuC:-LnJMrQz8GkrUctWGQgi:bg8uqqt) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@donporter Could you create a matching PR in the main repo?
</blockquote></details>

https://github.com/oscarlab/graphene/pull/957

---

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yamahata — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
