### PR TITLE
Remove support for Intel SGX drivers version 1.8- and corresponding cleanup

### PR DESCRIPTION
**Pull request by dimakuv**
Previously, Graphene SGX driver tried to stay compatible with Intel SGX drivers of versions 1.8 and lower. This inflated GSGX driver codebase significantly. Given that Intel SGX driver v1.8 was released in 2017, we can deprecate it and only allow drivers v1.9+ (including DCAP driver).

Corresponding PR is https://github.com/oscarlab/graphene/pull/1328.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12)

### CODE REVIEW

**Review by yamahata — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12)* status: 0 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[gsgx.c, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M-w0OUx2omgyBZra_Ag:-M-w0OUx2omgyBZra_Ah:b-6ez6hy) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/252101c6ce0b2f40af1e18d3dee35ad383a54e15/gsgx.c#L48)):*
> ```C
> static const struct file_operations gsgx_fops = {
>     .owner = THIS_MODULE,
>     .open  = gsgx_open,
> ```

no close method?
If so, I would enable/disable fsgsbase by gsgx_setup/teardown().

open method will be noop. it is only to prevent kernel from rmmod gsgx.ko.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12)* status: 0 of 14 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[gsgx.c, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M-w0OUx2omgyBZra_Ag:-M-w6zDK9tuqO6m-OKu2:bcuzqmb) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/252101c6ce0b2f40af1e18d3dee35ad383a54e15/gsgx.c#L48)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

no close method?
If so, I would enable/disable fsgsbase by gsgx_setup/teardown().

open method will be noop. it is only to prevent kernel from rmmod gsgx.ko.

</blockquote></details>

Done. I'm not proficient in kernel modules, hopefully I did it correctly.

**Review by yamahata — COMMENTED** [review]
only one nitpick. otherwise looks good to me.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-:-M-w9W4Y7Ul2uuP-m0go:briqqnt)* status: 0 of 14 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[gsgx.c, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M-w0OUx2omgyBZra_Ag:-M-w9IJdCZ21FwDl16D6:b-3acb94) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/252101c6ce0b2f40af1e18d3dee35ad383a54e15/gsgx.c#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I'm not proficient in kernel modules, hopefully I did it correctly.
</blockquote></details>

just .owner = THIS_MODULE.
gsgx_open is no needed. you can leave it NULL. which is effectively nop.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12)* status: 0 of 14 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[gsgx.c, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M-w0OUx2omgyBZra_Ag:-M-wALcZDmnGl-EwZCHt:bx49fe7) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/252101c6ce0b2f40af1e18d3dee35ad383a54e15/gsgx.c#L48)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

just .owner = THIS_MODULE.
gsgx_open is no needed. you can leave it NULL. which is effectively nop.
</blockquote></details>

Done. Looks like I can completely remove `.open = ...`: https://stackoverflow.com/questions/54250240/mandatory-functions-of-struct-file-operations.

**Review by yamahata — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12)* status: 0 of 14 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[README.rst, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M-wE1jz6Db_NQhrkbw5:-M-wE1k-2vb7PdjINzHs:bjpb6ik) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/183b95d88ba19ec495220e55dfe512cf929efb28/README.rst#L30)):*
> ```
> |
> ```
nitpick: ||
or rst format issue?
___
*[README.rst, line 31 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M-wE7h72U26UEpl04uI:-M-wE7h72U26UEpl04uJ:b-zgzv7z) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/183b95d88ba19ec495220e55dfe512cf929efb28/README.rst#L31)):*
> ```
> |
> ```
ditto.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[gsgx.h, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-VW8TCz6m3sh9xfo3:-M0-VW8TCz6m3sh9xfo4:b-uhay8m) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.h#L3)):*
> ```
> chiache-che.tsai
> ```

:thinking: 
___
*[gsgx.h, line 26 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-Uvo43SmmZxUEr4Ip:-M0-Uvo50ekzsYbUtRQg:b-vklsvh) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.h#L26)):*
> ```objc
> #define GSGX_MINOR MISC_DYNAMIC_MINOR
> 
> /* SGX_INVALID_LICENSE renamed to SGX_INVALID_EINITTOKEN in SGX driver 2.1:
> ```

`renamed to` -> `was renamed to`
___
*[gsgx.h, line 29 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-V49153Rldevt3IQ5:-M0-V49153Rldevt3IQ6:b-fkxirj) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.h#L29)):*
> ```objc
>  *   https://github.com/intel/linux-sgx-driver/commit/a7997dafe184d7d527683d8d46c4066db205758d */
> #ifndef SGX_INVALID_LICENSE
> # ifndef SGX_INVALID_EINITTOKEN
> ```

No need for nesting this, you can use `#if !defined() && ...` syntax
___
*[gsgx.c, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-VeCUCW3sAYHFS9NV:-M0-VeCUCW3sAYHFS9NW:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.c#L3)):*
> ```C
> /*
>  * (C) Copyright 2015 Intel Corporation
>  * Author: Chia-Che Tsai <chiache-che.tsai@intel.com>
> ```

ditto
___
*[gsgx.c, line 12 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-VoQN7m_PMxdB5y9o:-M0-VoQN7m_PMxdB5y9p:b-2b4bo8) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.c#L12)):*
> ```C
> 
> /*
>  * The only action this driver does is to enable FSGSBASE instruction in user
> ```

`is to enable` -> `is enabling`
___
*[gsgx.c, line 67 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-Yzqc9C8LKXOcKXsl:-M0-Yzqc9C8LKXOcKXsm:b-a27qi3) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.c#L67)):*
> ```C
>     if (ret) {
>         pr_err("misc_register() failed\n");
>         gsgx_dev.this_device = NULL;
> ```

I don't think this is needed, I guess `gsgx_teardown` function won't be called if the initialization failed.
___
*[README.rst, line 18 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-dk_P7h0k_opwRNmf:-M0-dk_P7h0k_opwRNmg:b-u0zgj7) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/README.rst#L18)):*
> ```reStructuredText
> to enable the ``FSGSBASE`` instruction in user space. Older Linux versions do not allow to enable
> this instruction from user land, thus the need for this driver. In the future, the support for old
> Linux versions may be dropped, and this driver won't be needed.
> ```

Hmm, is this already supported in Linux? When I checked the last time the support wasn't merged and didn't look like it will.
___
*[README.rst, line 25 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-eGGr8PMB7AJEu5O4:-M0-eGGr8PMB7AJEu5O5:btuibw3) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/README.rst#L25)):*
> ```reStructuredText
> 
> - DCAP driver <https://github.com/intel/SGXDataCenterAttestationPrimitives>
> - Older out-of-tree non-DCAP driver, only versions 1.9+ <https://github.com/intel/linux-sgx-driver>
> ```

I think formatting of the links got different than intended (the angle brackets are rendered as-is)
___
*[README.rst, line 31 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-ejog1txy0Jnpsu6n:-M0-ejog1txy0Jnpsu6o:b-j0hvbq) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/README.rst#L31)):*
> ```reStructuredText
> 
>     sudo rmmod gsgx || true
>     sudo rmmod graphene_sgx || true
> ```

Is this `rmmod` needed? Looks like a legacy leftover.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12)* status: 11 of 14 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[gsgx.h, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-VW8TCz6m3sh9xfo3:-M0-jumu8OfM4F7P8e2_:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.h#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> chiache-che.tsai
> ```

:thinking: 
</blockquote></details>

Done.
___
*[gsgx.h, line 26 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-Uvo43SmmZxUEr4Ip:-M0-jzH59nnCQ_9Etw4J:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.h#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`renamed to` -> `was renamed to`
</blockquote></details>

Done.
___
*[gsgx.h, line 29 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-V49153Rldevt3IQ5:-M0-kiqV4fEcpLYGzW9a:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.h#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No need for nesting this, you can use `#if !defined() && ...` syntax
</blockquote></details>

Done.
___
*[gsgx.c, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-VeCUCW3sAYHFS9NV:-M0-lBKt3-1bfyuC43i1:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.c#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[gsgx.c, line 12 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-VoQN7m_PMxdB5y9o:-M0-lF3o0ggis_lXudoy:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.c#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`is to enable` -> `is enabling`
</blockquote></details>

Done.
___
*[gsgx.c, line 67 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-Yzqc9C8LKXOcKXsl:-M0-lIe93f5x_ZSl9Z1h:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/gsgx.c#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't think this is needed, I guess `gsgx_teardown` function won't be called if the initialization failed.
</blockquote></details>

Done.
___
*[README.rst, line 18 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-dk_P7h0k_opwRNmf:-M0-ldmc50bPHaU5GN1n:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/README.rst#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, is this already supported in Linux? When I checked the last time the support wasn't merged and didn't look like it will.
</blockquote></details>

Done.
___
*[README.rst, line 25 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-eGGr8PMB7AJEu5O4:-M0-imzSD_J51ZYR8OfZ:bkq2qf3) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/README.rst#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think formatting of the links got different than intended (the angle brackets are rendered as-is)
</blockquote></details>

I followed the style in our top-most README: https://github.com/oscarlab/graphene/blob/master/README.rst. I don't know why they decided to use angle brackets, but I'm just sticking to it.
___
*[README.rst, line 31 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-ejog1txy0Jnpsu6n:-M0-izPg53jmcFx5yVjj:b-lfq7ol) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/README.rst#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this `rmmod` needed? Looks like a legacy leftover.
</blockquote></details>

This is for legacy, so that people remove the previously-named driver the first time they use this PR. I added a comment on this.

**Review by mkow — DISMISSED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[README.rst, line 25 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12#-M0-eGGr8PMB7AJEu5O4:-M0-rgFS1pt1G95R47Xl:bgifabe) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/fbbfb383c467acb7c3f99ffad94e3a8a0b1ff265/README.rst#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I followed the style in our top-most README: https://github.com/oscarlab/graphene/blob/master/README.rst. I don't know why they decided to use angle brackets, but I'm just sticking to it.
</blockquote></details>

Probably a bug. Anyways, resolving.

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by yamahata — APPROVED** [review]
> Reviewed 10 of 13 files at r1, 1 of 3 files at r2, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/12)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
