### PR TITLE
Rewrite link-intel-driver.py in python3

### PR DESCRIPTION
**Pull request by jiazhang0**
When creating a graphene development environment in container, it is
best to install the minimal packages. Currently, graphene has removed
the dependency on python2.

Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/8)

### CODE REVIEW

**Review by yamahata — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/8)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

**Review by dimakuv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/8)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/8#-LrVyY4HDbKH-30JjHGu:-LrVyY4IAhT3wREpIYbM:bdcpoot) (no related file):*
This file is so badly written... It would be nice if you will re-write it in a more Pythonic way (similar to e.g. `pal-sgx-sign`). But I'm not blocking on this, doing minor modifications to move to Python3 is also nice.

---

**Review by yamahata — COMMENTED** [review]
looks good to me.
refactoring would be another PR.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/8#-:-Lrp_ocF6roEnBFmqKGr:b-7i4uu4)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by yamahata — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/8#-:-Lrp_w-d3_Cd6gr9nNI2:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/8)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/8)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/8)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Pull request merged**
